Update deploy-terraform.yml

diff --git a/.github/workflows/deploy-terraform.yml b/.github/workflows/deploy-terraform.yml
--- a/.github/workflows/deploy-terraform.yml
+++ b/.github/workflows/deploy-terraform.yml
@@ -109,7 +109,22 @@ jobs:
         working-directory: ./terraform
         shell: bash
         run: |
-         echo "AZURE_STORAGE_ACCOUNT=$(terraform output -raw storage_account_name)" >> $GITHUB_ENV
-         echo "CONTAINER_NAME=$(terraform output -raw container_name)" >> $GITHUB_ENV
-         echo "AZURE_STORAGE_KEY=$(terraform output -raw storage_account_primary_key)" >> $GITHUB_ENV
+         RESOURCE_GROUP_NAME=$(terraform output -raw resource_group_name)
+         STORAGE_ACCOUNT_NAME=$(terraform output -raw storage_account_name)
+         CONTAINER_NAME=$(terraform output -raw container_name)
+
+         AZURE_STORAGE_KEY=$(az storage account keys list \
+         --resource-group "$RESOURCE_GROUP_NAME" \
+         --account-name "$STORAGE_ACCOUNT_NAME" \
+         --query '[0].value' -o tsv)
+
+         if [[ -z "$AZURE_STORAGE_KEY" ]]; then
+         echo "::error::Failed to get storage account key!"
+         exit 1
+         fi
+
+         echo "AZURE_STORAGE_ACCOUNT=$STORAGE_ACCOUNT_NAME" >> $GITHUB_ENV
+         echo "CONTAINER_NAME=$CONTAINER_NAME" >> $GITHUB_ENV
+         echo "::add-mask::$AZURE_STORAGE_KEY"
+         echo "AZURE_STORAGE_KEY=$AZURE_STORAGE_KEY" >> $GITHUB_ENV
 
